version: "3.1"
services:
  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    networks:
      - servidores     
    volumes:
      - /home/ubuntu/jenkins:/var/jenkins_home
networks:
  servidores:
    driver: bridge
